databases:
  - name: airbnb-backend
    databaseName: airbnb-backend
    user: airbnb-backend
    region: singapore

services:
  - type: web
    name: airbnb-backend
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnb-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
